-- MySQL Script generated by MySQL Workbench
-- 01/29/16 17:28:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projects
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projects
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projects` DEFAULT CHARACTER SET utf8 ;
USE `projects` ;

-- -----------------------------------------------------
-- Table `projects`.`leader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projects`.`leader` ;

CREATE TABLE IF NOT EXISTS `projects`.`leader` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `department` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projects`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projects`.`project` ;

CREATE TABLE IF NOT EXISTS `projects`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `days` INT NULL,
  `cost` FLOAT(10,2) NULL,
  `status` ENUM('En Proceso', 'Terminado', 'Abandonado') NULL,
  `leader_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `leader_id1`),
  INDEX `fk_project_leader1_idx` (`leader_id1` ASC),
  CONSTRAINT `fk_project_leader1`
    FOREIGN KEY (`leader_id1`)
    REFERENCES `projects`.`leader` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `projects` ;

-- -----------------------------------------------------
-- Placeholder table for view `projects`.`the_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projects`.`the_projects` (`name_project` INT, `name` INT, `days` INT, `end_date` INT, `cost` INT);

-- -----------------------------------------------------
-- Placeholder table for view `projects`.`theprojects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projects`.`theprojects` (`name_project` INT, `name` INT, `days` INT, `end_date` INT, `cost` INT);

-- -----------------------------------------------------
-- View `projects`.`the_projects`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `projects`.`the_projects` ;
DROP TABLE IF EXISTS `projects`.`the_projects`;
USE `projects`;
CREATE  OR REPLACE VIEW `the_projects` AS 
SELECT project.name as name_project,concat(leader.name," ",leader.lastname) as name,days,end_date,cost from project,leader where project.end_date >=curdate() and leader_id1=idleader;

-- -----------------------------------------------------
-- View `projects`.`theprojects`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `projects`.`theprojects` ;
DROP TABLE IF EXISTS `projects`.`theprojects`;
USE `projects`;
CREATE  OR REPLACE VIEW `theprojects` AS
SELECT project.name as name_project,concat(leader.name," ",leader.lastname) as name,days,end_date,cost from leader join project on project.leader_id1 = leader.id where project.end_date >=curdate();

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
